Import Libraries

In [1]:
import pandas as pd

Load your dataset - excel / csv

In [2]:
df=pd.read_csv("Telecom_Network_Data.csv")

Basic overview

In [3]:
df.head()

,timestamp,tower_id,users_connected,download_speed,upload_speed,latency,weather,congestion
0,01-01-2025 00:00,1,152,80.67,9.99,158.14,Clear,0
1,01-01-2025 01:00,1,171,19.82,3.85,174.57,Clear,0
2,01-01-2025 02:00,1,713,66.83,3.76,147.18,Snow,0
3,01-01-2025 03:00,1,435,22.27,9.99,67.81,Clear,0
4,01-01-2025 04:00,1,797,7.19,26.71,85.97,Clear,0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3605 entries, 0 to 3604
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   timestamp        3605 non-null   str
 1   tower_id         3605 non-null   int64
 2   users_connected  3605 non-null   int64
 3   download_speed   3605 non-null   float64
 4   upload_speed     3605 non-null   float64
 5   latency          3605 non-null   float64
 6   weather          3605 non-null   str
 7   congestion       3605 non-null   int64
dtypes: float64(3), int64(3), str(2)
memory usage: 225.4 KB

In [5]:
df.tail()

,timestamp,tower_id,users_connected,download_speed,upload_speed,latency,weather,congestion
3600,30-01-2025 20:00,5,705,77.69,19.12,41.75,Clear,0
3601,30-01-2025 21:00,5,768,76.41,37.60,75.55,Clear,0
3602,30-01-2025 22:00,5,419,76.23,9.69,12.56,Clear,0
3603,30-01-2025 23:00,5,738,76.77,1.47,192.21,Clear,0
3604,31-01-2025 00:00,5,797,92.02,20.93,61.23,Clear,0

In [6]:
df.shape

(3605, 8)

In [7]:
df.columns

Index(['timestamp', 'tower_id', 'users_connected', 'download_speed',
       'upload_speed', 'latency', 'weather', 'congestion'],
      dtype='str')

In [8]:
df.describe()

,tower_id,users_connected,download_speed,upload_speed,latency,congestion
count,3605.00000,3605.000000,3605.000000,3605.000000,3605.000000,3605.000000
mean,3.00000,531.091817,52.087623,25.167176,105.100416,0.056311
std,1.41441,275.722937,27.343367,13.995882,54.884386,0.230553
min,1.00000,50.000000,5.000000,1.050000,10.030000,0.000000
25%,2.00000,294.000000,28.480000,13.380000,58.080000,0.000000
50%,3.00000,538.000000,52.510000,25.100000,105.180000,0.000000
75%,4.00000,765.000000,75.250000,37.010000,153.870000,0.000000
max,5.00000,999.000000,99.990000,49.990000,199.950000,1.000000

Handle Missing Values

In [9]:
#check missing values
df.isnull().sum()
#fill missing vlaues
df['users_connected'] = df['users_connected'].fillna(0)

In [10]:
df['download_speed'] = df['download_speed'].fillna(df['download_speed'].mean())

In [11]:
df['upload_speed'] = df['upload_speed'].fillna(df['upload_speed'].mean())

In [12]:
df['latency'] = df['latency'].fillna(df['latency'].mean())

In [13]:
df['weather'] = df['weather'].fillna("Unknown")

Basic Filtering

In [14]:
#high latency cases
high_latency = df[df['latency'] > 100]
high_latency.head()

,timestamp,tower_id,users_connected,download_speed,upload_speed,latency,weather,congestion
0,01-01-2025 00:00,1,152,80.67,9.99,158.14,Clear,0
1,01-01-2025 01:00,1,171,19.82,3.85,174.57,Clear,0
2,01-01-2025 02:00,1,713,66.83,3.76,147.18,Snow,0
5,01-01-2025 05:00,1,749,39.80,23.35,159.18,Clear,0
6,01-01-2025 06:00,1,616,98.41,23.87,173.39,Clear,0

In [15]:
#low download speed
low_speed = df[df['download_speed'] < 10]
low_speed.head()

,timestamp,tower_id,users_connected,download_speed,upload_speed,latency,weather,congestion
4,01-01-2025 04:00,1,797,7.19,26.71,85.97,Clear,0
8,01-01-2025 08:00,1,826,6.52,12.31,55.79,Clear,0
16,01-01-2025 16:00,1,521,6.34,10.74,145.15,Rain,0
62,03-01-2025 14:00,1,520,7.62,29.36,93.31,Clear,0
104,05-01-2025 08:00,1,222,9.10,44.67,110.26,Storm,0

In [16]:
#specific tower
tower_data = df[df['tower_id'].isin([1, 2, 3])]
tower_data.head()

,timestamp,tower_id,users_connected,download_speed,upload_speed,latency,weather,congestion
0,01-01-2025 00:00,1,152,80.67,9.99,158.14,Clear,0
1,01-01-2025 01:00,1,171,19.82,3.85,174.57,Clear,0
2,01-01-2025 02:00,1,713,66.83,3.76,147.18,Snow,0
3,01-01-2025 03:00,1,435,22.27,9.99,67.81,Clear,0
4,01-01-2025 04:00,1,797,7.19,26.71,85.97,Clear,0

Simple analysis

In [17]:
#average speeds
df[['download_speed','upload_speed']].mean()

#users vs speed
df[['users_connected', 'download_speed']].corr()

                 users_connected  download_speed
users_connected         1.000000        0.017423
download_speed          0.017423        1.000000

In [18]:
#weather impact
df.groupby('weather')['download_speed'].mean()

weather
Clear    52.055165
Rain     52.955545
Snow     50.682235
Storm    52.586484
Name: download_speed, dtype: float64

In [19]:
#average latency
df['latency'].mean()

np.float64(105.1004160887656)

In [20]:
#average speeds
df[['download_speed','upload_speed']].mean()

download_speed    52.087623
upload_speed      25.167176
dtype: float64

Save Cleaned Data

In [21]:
df.to_csv("cleaned_telecom_data.csv", index=False)